@extends('layouts.company-workspace')
@section('title', 'الفواتير')
@section('content')
<x-layout.page-header :title="'الفواتير - '.($company->name_ar ?? $company->legal_name_ar)" subtitle="محرك الفواتير الداخلي مع حالة جوفوتارا والاستيراد.">
    <x-slot:actions>@if($company->featureKeys->contains('code', 'JOFOTARA_SYNC'))<a class="btn btn-outline-secondary" href="{{ route('company.invoices.import.index', $company) }}">استيراد/مزامنة فواتير سابقة</a>@endif<a class="btn btn-primary" href="{{ route('company.invoices.create', $company) }}">فاتورة جديدة</a></x-slot:actions>
</x-layout.page-header>
<form class="card card-body mb-3"><div class="row g-2"><div class="col-md-3"><input name="search" class="form-control" placeholder="بحث برقم الفاتورة أو جهة الاتصال" value="{{ request('search') }}"></div><div class="col-md-2"><select name="status" class="form-select"><option value="">كل الحالات</option>@foreach(['draft'=>'مسودة','ready'=>'جاهزة للإرسال','submitted'=>'مرسلة للفوترة الوطنية','cancelled'=>'ملغاة'] as $value => $label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><select name="source" class="form-select"><option value="">كل المصادر</option><option value="local" @selected(request('source')==='local')>محلي</option><option value="jofotara_import" @selected(request('source')==='jofotara_import')>استيراد جوفوتارا</option></select></div><div class="col-md-3"><select name="invoice_type" class="form-select"><option value="">كل الأنواع</option>@foreach(['tax_invoice'=>'فاتورة ضريبية','simplified_invoice'=>'فاتورة مبسطة','credit_note'=>'إشعار دائن','debit_note'=>'إشعار مدين'] as $value => $label)<option value="{{ $value }}" @selected(request('invoice_type')===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100">تصفية</button></div></div></form>
<div class="card"><table class="table mb-0"><tr><th>الرقم</th><th>الجهة</th><th>الحالة المحلية</th><th>جوفوتارا</th><th>المصدر</th><th>تاريخ الإرسال</th><th>الإجمالي</th><th></th></tr>@foreach($invoices as $invoice)<tr><td>{{ $invoice->invoice_number }}</td><td>{{ $invoice->contact?->name_ar ?: '—' }}</td><td>{{ $invoice->status }}</td><td>{{ $invoice->jofotara_status ?: 'غير مرسلة' }}</td><td>{{ $invoice->source === 'jofotara_import' ? 'استيراد جوفوتارا' : 'محلي' }}</td><td>{{ $invoice->jofotara_submitted_at?->format('Y-m-d H:i') ?: '—' }}</td><td>{{ $invoice->grand_total }} {{ $invoice->currency }}</td><td><a href="{{ route('company.invoices.show', [$company, $invoice]) }}">عرض</a></td></tr>@endforeach</table></div>{{ $invoices->links() }}
@endsection
