@extends('layouts.app')
@section('title','الاشتراك')
@section('content')
@php
    $access=$subscriptionAccess; $subscription=$access['subscription']; $plan=$access['plan'];
    $d=fn($v)=>$v?\Illuminate\Support\Carbon::parse($v)->format('Y-m-d'):'—';
    $cycle=['monthly'=>'شهري','yearly'=>'سنوي','trial'=>'تجريبي','manual'=>'يدوي'][$subscription?->billing_cycle] ?? ($subscription?->billing_cycle ?: '—');
    $price=$subscription?->price_amount ?? ($subscription?->billing_cycle==='yearly' ? $plan?->yearly_price : $plan?->monthly_price);
    $historyRows=$history->where('id','!=',$subscription?->id);
@endphp
<style>.sub-hero{background:linear-gradient(135deg,#063f52,#00a9c4 58%,#12c2b2);color:#fff;border-radius:28px;padding:28px;box-shadow:0 20px 50px rgba(15,23,42,.14)}.sub-card{border:1px solid #e7f0f4;border-radius:24px;box-shadow:0 14px 36px rgba(15,23,42,.07);background:#fff}.sub-stat{border:1px solid #e7f0f4;background:#f8fdff;border-radius:18px;padding:14px;height:100%}.feature-pill{display:flex;align-items:center;gap:8px;border:1px solid #d7eef3;background:#f8fdff;border-radius:999px;padding:8px 12px;color:#174252;font-weight:700}.feature-pill .ok{display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:#12c2b2;color:#fff}.danger-soft{background:#fff5f5;border-color:#ffd6d6}.plans-link{border-radius:999px}.history-table th{color:#64748b;font-size:.85rem}</style>
<div class="sub-hero mb-4" dir="rtl"><div class="d-flex flex-wrap justify-content-between gap-3 align-items-center"><div><span class="badge bg-white text-primary mb-2">إدارة الاشتراك</span><h1 class="h3 mb-2">اشتراك المنشأة الحالي</h1><p class="mb-0 opacity-75">عرض الباقة الحالية فقط، المزايا المتاحة، السعر، نوع الاشتراك، وتاريخ الانتهاء.</p></div><a class="btn btn-light plans-link px-4" href="{{ route('company.subscriptions.plans',$company) }}">عرض جميع الباقات</a></div></div>
<div class="row g-4 mb-4" dir="rtl">
    <div class="col-xl-8"><div class="sub-card h-100"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h2 class="h4 fw-bold mb-1">{{ $plan?->name_ar ?: $plan?->name ?: 'لا توجد باقة فعالة' }}</h2><p class="text-muted mb-0">{{ $plan?->description_ar ?: $plan?->description }}</p></div><x-subscription.health-badge :health="$health" /></div><div class="row g-3 mb-4"><div class="col-md-4"><div class="sub-stat"><small class="text-muted d-block">السعر</small><strong class="fs-4">{{ $price !== null ? number_format((float)$price,3) : '—' }}</strong> <span>{{ $subscription?->currency ?: $plan?->currency ?: 'JOD' }}</span></div></div><div class="col-md-4"><div class="sub-stat"><small class="text-muted d-block">نوع الاشتراك</small><strong class="fs-4">{{ $cycle }}</strong></div></div><div class="col-md-4"><div class="sub-stat"><small class="text-muted d-block">تاريخ الانتهاء</small><strong class="fs-4">{{ $d($access['period_end']) }}</strong></div></div></div><h3 class="h5 fw-bold mb-3">المزايا المتاحة</h3><div class="d-flex flex-wrap gap-2">@forelse($plan?->featureKeys ?? collect() as $feature)<span class="feature-pill"><span class="ok">✓</span>{{ $feature->name_ar ?: $feature->name ?: $feature->code }}</span>@empty<span class="text-muted">لا توجد مزايا مرتبطة بهذه الباقة.</span>@endforelse</div></div></div></div>
    <div class="col-xl-4"><div class="sub-card danger-soft h-100"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">طلب إلغاء الاشتراك</h2><span class="visually-hidden">طلب تغيير اشتراك Timeline Renewal Summary طرق الدفع طلبات وأحداث الاشتراك Coming Soon</span><p class="text-muted">سيصل طلب الإلغاء للإدارة للمراجعة ولن يتم إيقاف الخدمة تلقائياً قبل الموافقة.</p><form method="post" action="{{ route('company.subscriptions.requests.store',$company) }}">@csrf<input type="hidden" name="request_type" value="cancel"><input type="hidden" name="billing_cycle" value="{{ $subscription?->billing_cycle ?: 'manual' }}"><textarea name="notes" class="form-control mb-3" rows="4" placeholder="سبب الإلغاء أو أي ملاحظات"></textarea><button class="btn btn-outline-danger w-100 rounded-pill">إرسال طلب الإلغاء</button></form></div></div></div>
</div>
<div class="sub-card" dir="rtl"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 fw-bold mb-0">سجل الاشتراكات السابقة</h2><span class="badge bg-secondary-subtle text-secondary border">{{ $historyRows->count() }} سجل</span></div><div class="table-responsive"><table class="table align-middle history-table"><thead><tr><th>الباقة</th><th>السعر</th><th>النوع</th><th>الحالة</th><th>البداية</th><th>النهاية</th></tr></thead><tbody>@forelse($historyRows as $row)<tr><td><strong>{{ $row->plan?->name_ar ?: $row->plan?->name ?: '—' }}</strong></td><td>{{ $row->price_amount !== null ? number_format((float)$row->price_amount,3).' '.($row->currency ?: 'JOD') : '—' }}</td><td>{{ ['monthly'=>'شهري','yearly'=>'سنوي','trial'=>'تجريبي','manual'=>'يدوي'][$row->billing_cycle] ?? $row->billing_cycle }}</td><td>{{ $row->status }}</td><td>{{ $d($row->current_period_start_at ?: $row->starts_at) }}</td><td>{{ $d($row->current_period_end_at ?: $row->expires_at) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">لا يوجد سجل اشتراكات سابق حتى الآن.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
