@extends('layouts.app')
@section('title','الاشتراك')
@section('content')
@php $access=$subscriptionAccess; $subscription=$access['subscription']; $plan=$access['plan']; $d=fn($v)=>$v?\Illuminate\Support\Carbon::parse($v)->format('Y-m-d'):'—'; @endphp
<x-layout.page-header title="الاشتراك" subtitle="عرض الاشتراك وطلب ترقية أو تجديد بدون تنفيذ دفع أو تغيير تلقائي." />
<div class="row g-4 mb-4">
    <div class="col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-start mb-3"><h2 class="h5 fw-bold mb-0">الاشتراك الحالي</h2><x-subscription.health-badge :health="$health" /></div><div class="row g-2"><div class="col-md-6"><x-info-row label="الباقة" :value="$plan?->name_ar ?: $plan?->name ?: '—'"/></div><div class="col-md-6"><x-info-row label="شهري/سنوي" :value="$subscription?->billing_cycle ?: '—'"/></div><div class="col-md-6"><x-info-row label="بداية الفترة" :value="$d($access['period_start'])"/></div><div class="col-md-6"><x-info-row label="نهاية الفترة" :value="$d($access['period_end'])"/></div><div class="col-md-6"><x-info-row label="فترة السماح" :value="$d($access['grace_end'])"/></div><div class="col-md-6"><x-info-row label="Auto Renew" :value="$subscription?->auto_renew ? 'مفعل' : 'غير مفعل'"/></div></div><h3 class="h6 fw-bold mt-4">المزايا</h3><div class="d-flex flex-wrap gap-2">@forelse($plan?->featureKeys ?? collect() as $feature)<span class="badge bg-primary-subtle text-primary border">{{ $feature->name_ar ?: $feature->code }}</span>@empty<span class="text-muted">لا توجد مزايا.</span>@endforelse</div></div></div></div>
    <div class="col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">Timeline</h2><x-subscription.timeline :items="$timeline" /></div></div></div>
</div>
<div class="row g-4 mb-4">
    <div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">Renewal Summary</h2><x-info-row label="آخر عملية" :value="$renewalSummary['label']"/><x-info-row label="التاريخ" :value="$renewalSummary['date']"/><x-info-row label="النوع" :value="$renewalSummary['type']"/><x-info-row label="المصدر" :value="$renewalSummary['source']"/></div></div></div>
    <div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 fw-bold mb-0">طرق الدفع</h2><span class="badge bg-secondary">Coming Soon</span></div><div class="d-flex flex-wrap gap-2">@foreach($paymentMethods as $method)<span class="payment-pill">{{ $method }}</span>@endforeach</div></div></div></div>
    <div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">طلب تغيير اشتراك</h2><form method="post" action="{{ route('company.subscriptions.requests.store',$company) }}">@csrf<select name="request_type" class="form-select mb-2" required><option value="upgrade">ترقية</option><option value="downgrade">تخفيض</option><option value="renewal">تجديد</option><option value="cancel">إلغاء</option></select><select name="requested_plan_id" class="form-select mb-2"><option value="">اختر الباقة عند الحاجة</option>@foreach($plans as $p)<option value="{{ $p->id }}">{{ $p->name_ar ?: $p->name }}</option>@endforeach</select><select name="billing_cycle" class="form-select mb-2"><option value="monthly">monthly</option><option value="yearly">yearly</option><option value="manual">manual</option></select><textarea name="notes" class="form-control mb-3" rows="3" placeholder="ملاحظات اختيارية"></textarea><button class="btn btn-primary w-100">إرسال الطلب</button></form></div></div></div>
</div>
<div class="row g-4"><div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">سجل الاشتراكات السابقة</h2><div class="table-responsive"><table class="table"><thead><tr><th>الباقة</th><th>الدورة</th><th>الحالة</th><th>البداية</th><th>النهاية</th></tr></thead><tbody>@foreach($history as $row)<tr><td>{{ $row->plan?->name_ar ?: $row->plan?->name }}</td><td>{{ $row->billing_cycle }}</td><td>{{ $row->status }}</td><td>{{ $d($row->current_period_start_at) }}</td><td>{{ $d($row->current_period_end_at) }}</td></tr>@endforeach</tbody></table></div></div></div></div><div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">طلبات وأحداث الاشتراك</h2>@forelse($requests as $r)<div class="border rounded p-3 mb-2"><strong>{{ $r->request_type }}</strong> — {{ $r->status }}<br><small class="text-muted">{{ $r->requestedPlan?->name_ar ?: '—' }} / {{ $r->created_at->format('Y-m-d') }}</small></div>@empty<p class="text-muted">لا توجد طلبات بعد.</p>@endforelse<hr>@forelse($events as $event)<div class="small text-muted mb-1">{{ str($event->event_type)->headline() }} — {{ $d($event->occurred_at) }}</div>@empty<div class="small text-muted">لا توجد أحداث بعد.</div>@endforelse</div></div></div></div>
@endsection
