@extends('layouts.app')
@section('title', 'إدارة اشتراكات المنشأة')
@section('content')
@php
    $access = $subscriptionAccess;
    $subscription = $access['subscription'];
    $plan = $access['plan'];
    $d = fn ($v) => $v ? \Illuminate\Support\Carbon::parse($v)->format('Y-m-d') : '—';
    $money = fn ($a, $c) => $a !== null ? number_format((float) $a, 3).' '.($c ?: 'JOD') : '—';
    $cycle = ['monthly' => 'شهري', 'yearly' => 'سنوي', 'trial' => 'تجريبي', 'manual' => 'يدوي'][$subscription?->billing_cycle] ?? ($subscription?->billing_cycle ?: '—');
    $price = $subscription?->price_amount ?? ($subscription?->billing_cycle === 'yearly' ? $plan?->yearly_price : $plan?->monthly_price);
    $historyRows = $history->getCollection()->where('id', '!=', $subscription?->id);
@endphp
<style>.admin-sub-hero{background:linear-gradient(135deg,#081f32,#00a9c4 60%,#12c2b2);color:#fff;border-radius:28px;padding:28px;box-shadow:0 20px 50px rgba(15,23,42,.14)}.admin-card{border:1px solid #e7f0f4;border-radius:24px;box-shadow:0 14px 36px rgba(15,23,42,.07);background:#fff}.admin-stat{border:1px solid #e7f0f4;background:#f8fdff;border-radius:18px;padding:14px;height:100%}.feature-pill{display:flex;align-items:center;gap:8px;border:1px solid #d7eef3;background:#f8fdff;border-radius:999px;padding:8px 12px;color:#174252;font-weight:700}.feature-pill .ok{display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:#12c2b2;color:#fff}.admin-actions .btn{border-radius:999px}.plans-strip{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(280px,1fr);gap:16px;overflow-x:auto;padding-bottom:12px;scroll-snap-type:x mandatory}.mini-plan{scroll-snap-align:start;border:1px solid #e7f0f4;border-radius:22px;background:#fff;padding:18px;position:relative}.mini-plan.current{border-color:#12c2b2;background:#f8fffe}.pchk,.pxx{display:inline-grid;place-items:center;width:20px;height:20px;border-radius:50%;font-weight:900;color:#fff;margin-inline-end:6px}.pchk{background:#12c2b2}.pxx{background:#e45858}@media(min-width:1200px){.plans-strip{grid-auto-columns:calc((100% - 32px)/3)}}</style>
<div class="admin-sub-hero mb-4" dir="rtl"><div class="d-flex flex-wrap justify-content-between align-items-center gap-3"><div><span class="badge bg-white text-primary mb-2">إدارة الاشتراك</span><h1 class="h3 mb-2">{{ $company->name_ar }}</h1><p class="mb-0 opacity-75">نفس تجربة صفحة الشركة: الباقة الحالية، المزايا، السعر، نوع الاشتراك، تاريخ الانتهاء، سجل الاشتراكات، وإجراءات الإدارة.</p></div><a class="btn btn-light rounded-pill px-4" href="{{ route('admin.companies.show', $company) }}">عودة للمنشأة</a></div></div>
<div class="row g-4 mb-4" dir="rtl">
    <div class="col-xl-8"><div class="admin-card h-100"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h2 class="h4 fw-bold mb-1">{{ $plan?->name_ar ?: $plan?->name ?: 'لا توجد باقة فعالة' }}</h2><p class="text-muted mb-0">{{ $plan?->description_ar ?: $plan?->description }}</p></div><x-subscription.health-badge :health="$health" /></div><div class="row g-3 mb-4"><div class="col-md-3"><div class="admin-stat"><small class="text-muted d-block">السعر</small><strong class="fs-5">{{ $money($price, $subscription?->currency ?: $plan?->currency) }}</strong></div></div><div class="col-md-3"><div class="admin-stat"><small class="text-muted d-block">نوع الاشتراك</small><strong class="fs-5">{{ $cycle }}</strong></div></div><div class="col-md-3"><div class="admin-stat"><small class="text-muted d-block">تاريخ الانتهاء</small><strong class="fs-5">{{ $d($access['period_end']) }}</strong></div></div><div class="col-md-3"><div class="admin-stat"><small class="text-muted d-block">التجديد التلقائي</small><strong class="fs-5">{{ $subscription?->auto_renew ? 'مفعل' : 'غير مفعل' }}</strong></div></div></div><h3 class="h5 fw-bold mb-3">المزايا المتاحة</h3><div class="d-flex flex-wrap gap-2">@forelse($plan?->featureKeys ?? collect() as $feature)<span class="feature-pill"><span class="ok">✓</span>{{ $feature->name_ar ?: $feature->name ?: $feature->code }}</span>@empty<span class="text-muted">لا توجد مزايا مرتبطة.</span>@endforelse</div></div></div></div>
    <div class="col-xl-4"><div class="admin-card h-100"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">إجراءات الإدارة</h2><span class="visually-hidden">Renew Monthly Subscription Timeline Renewal Summary طرق الدفع Coming Soon Subscription Events</span><div class="d-grid gap-2 admin-actions"><form method="post" action="{{ route('admin.companies.subscriptions.renew', [$company, 'monthly']) }}">@csrf<button class="btn btn-outline-primary w-100">تجديد شهري</button></form><form method="post" action="{{ route('admin.companies.subscriptions.renew', [$company, 'yearly']) }}">@csrf<button class="btn btn-primary w-100">تجديد سنوي</button></form><form method="post" action="{{ route('admin.companies.subscriptions.toggle-auto-renew', $company) }}">@csrf<button class="btn btn-outline-info w-100">تفعيل/إيقاف التجديد التلقائي</button></form><form method="post" action="{{ route('admin.companies.subscriptions.cancel', $company) }}">@csrf<button class="btn btn-outline-danger w-100">إلغاء الاشتراك</button></form><form method="post" action="{{ route('admin.companies.subscriptions.reactivate', $company) }}">@csrf<button class="btn btn-outline-success w-100">إعادة تفعيل الاشتراك</button></form></div><hr><div class="small text-muted">الدفع: {{ $subscription?->payment_status ?: 'not_started' }} / {{ $subscription?->payment_provider ?: 'Placeholder' }}</div></div></div></div>
</div>
<div class="admin-card mb-4" dir="rtl"><div class="card-body p-4"><div class="d-flex justify-content-between flex-wrap gap-2 mb-3"><div><h2 class="h5 fw-bold mb-1">الباقات المتاحة للمنشأة</h2><p class="text-muted mb-0">عرض الباقات كسلايدر مع تحديد الباقة الحالية وعلامات ✓ و × لكل ميزة.</p></div><span class="badge bg-info text-dark">Upgrade / Downgrade</span></div><div class="plans-strip">@foreach($plans as $p)@php($featureIds=$p->featureKeys->pluck('id')->all())<div class="mini-plan {{ $plan?->id===$p->id ? 'current' : '' }}">@if($plan?->id===$p->id)<span class="badge bg-success mb-2">الباقة الحالية</span>@endif<h3 class="h5 fw-bold">{{ $p->name_ar ?: $p->name }}</h3><div class="fs-4 fw-black text-primary">{{ number_format((float)$p->monthly_price,3) }} <small>JOD/شهري</small></div><div class="text-muted small mb-3">{{ number_format((float)$p->yearly_price,3) }} JOD سنوي</div>@foreach($allFeatures as $feature)@php($has=in_array($feature->id,$featureIds,true))<div class="small mb-1"><span class="{{ $has ? 'pchk' : 'pxx' }}">{{ $has ? '✓' : '×' }}</span>{{ $feature->name_ar ?: $feature->name }}</div>@endforeach</div>@endforeach</div></div></div>
<div class="admin-card" dir="rtl"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 fw-bold mb-0">سجل الاشتراكات السابقة</h2><span class="badge bg-secondary-subtle text-secondary border">{{ $historyRows->count() }} سجل</span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>الباقة</th><th>السعر</th><th>النوع</th><th>الحالة</th><th>البداية</th><th>النهاية</th><th>المصدر</th><th>آخر تجديد</th></tr></thead><tbody>@forelse($historyRows as $row)<tr><td><strong>{{ $row->plan?->name_ar ?: $row->plan?->name ?: '—' }}</strong></td><td>{{ $money($row->price_amount, $row->currency) }}</td><td>{{ ['monthly'=>'شهري','yearly'=>'سنوي','trial'=>'تجريبي','manual'=>'يدوي'][$row->billing_cycle] ?? $row->billing_cycle }}</td><td>{{ $row->status }}</td><td>{{ $d($row->current_period_start_at ?: $row->starts_at) }}</td><td>{{ $d($row->current_period_end_at ?: $row->expires_at) }}</td><td>{{ $row->source ?: '—' }}</td><td>{{ $d($row->renewed_at) }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">لا يوجد سجل اشتراكات سابق.</td></tr>@endforelse</tbody></table></div>{{ $history->links() }}</div></div>
@endsection
