@extends('layouts.app')
@section('title', 'سجل النشاطات')
@section('content')
@php($routeCompanyId = $company->id ?? request()->route('company')?->id ?? request()->route('company') ?? auth()->user()?->company_id)
<div class="activity-hero" dir="rtl"><div class="d-flex gap-3 align-items-center"><div class="activity-icon bg-white text-info">📝</div><div><h1 class="h3 mb-2">سجل النشاطات</h1><p class="mb-0 opacity-75">تابع العمليات الإدارية داخل المنشأة بدون عرض بيانات حساسة.</p></div></div></div>
<form class="activity-filter card card-body mb-3" dir="rtl"><div class="row g-2 align-items-end"><div class="col-lg-3"><label class="form-label small text-muted">المستخدم</label><select name="user_id" class="form-select"><option value="">كل المستخدمين</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) request('user_id') === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div><div class="col-lg-3"><label class="form-label small text-muted">العملية</label><input name="action" class="form-control" placeholder="مثال: product أو invoice" value="{{ request('action') }}"></div><div class="col-lg-2"><label class="form-label small text-muted">التاريخ من</label><input name="date_from" type="date" class="form-control" value="{{ request('date_from') }}"></div><div class="col-lg-2"><label class="form-label small text-muted">التاريخ إلى</label><input name="date_to" type="date" class="form-control" value="{{ request('date_to') }}"></div><div class="col-lg-2"><button class="btn btn-primary w-100">🔎 تصفية</button></div></div></form>
@if($activities->isEmpty())
    <div class="empty-state" dir="rtl"><div class="empty-state-icon mb-3">📝</div><h2 class="h4">لا توجد نشاطات مطابقة</h2><p class="text-muted">غيّر الفلاتر أو جرّب نطاق تاريخ مختلف.</p></div>
@else
<div class="activity-card card" dir="rtl"><div class="activity-timeline">@foreach($activities as $activity)<div class="activity-item"><div class="activity-icon">{{ str_contains($activity->action, 'created') ? '➕' : (str_contains($activity->action, 'updated') ? '✏️' : (str_contains($activity->action, 'deactivated') ? '⏸️' : '📝')) }}</div><div><div class="d-flex flex-wrap gap-2 align-items-center justify-content-between"><div class="activity-action">{{ $activity->action }}</div><span class="activity-badge">{{ class_basename($activity->auditable_type) ?: 'System' }}</span></div><div class="activity-meta mt-2"><span>👤 {{ $activity->user?->name ?: 'النظام' }}</span><span class="mx-2">•</span><span>🕒 {{ $activity->created_at?->format('Y-m-d H:i') }}</span>@if($activity->auditable_id)<span class="mx-2">•</span><span>مرجع #{{ $activity->auditable_id }}</span>@endif</div></div></div>@endforeach</div></div><div class="mt-3">{{ $activities->links() }}</div>
@endif
@endsection
