@extends('layouts.app')
@section('title', 'سجل النشاطات')
@section('content')
@php($routeCompanyId = $company->id ?? request()->route('company')?->id ?? request()->route('company') ?? auth()->user()?->company_id)
<style>.activity-hero{background:linear-gradient(135deg,#00a9c4,#12c2b2);color:#fff;border-radius:24px;padding:24px;margin-bottom:18px;box-shadow:0 18px 42px rgba(15,23,42,.12)}.activity-filter,.activity-card{border:1px solid #e5eef4;border-radius:22px;box-shadow:0 12px 30px rgba(15,23,42,.06)}.activity-filter .form-control,.activity-filter .form-select{border-radius:14px}.activity-timeline{position:relative}.activity-item{display:grid;grid-template-columns:56px 1fr;gap:14px;padding:16px;border-bottom:1px dashed #e5eef4}.activity-item:last-child{border-bottom:0}.activity-icon{width:48px;height:48px;border-radius:16px;background:#eefcff;border:1px solid #d7eef3;display:grid;place-items:center;font-size:1.25rem}.activity-action{font-weight:800;color:#172033}.activity-meta{color:#64748b;font-size:.9rem}.activity-badge{display:inline-flex;border-radius:999px;padding:5px 10px;font-size:.8rem;border:1px solid #d7eef3;background:#f1f9fb;color:#0f6170}.empty-state{border:1px dashed #b7dce5;border-radius:22px;padding:42px;background:#f8fdff;text-align:center}.empty-state-icon{font-size:3rem}</style>
<div class="activity-hero" dir="rtl"><div class="d-flex gap-3 align-items-center"><div class="activity-icon bg-white text-info">📝</div><div><h1 class="h3 mb-2">سجل النشاطات</h1><p class="mb-0 opacity-75">تابع العمليات الإدارية داخل المنشأة بدون عرض بيانات حساسة.</p></div></div></div>
<form class="activity-filter card card-body mb-3" dir="rtl"><div class="row g-2 align-items-end"><div class="col-lg-3"><label class="form-label small text-muted">المستخدم</label><select name="user_id" class="form-select"><option value="">كل المستخدمين</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) request('user_id') === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div><div class="col-lg-3"><label class="form-label small text-muted">العملية</label><input name="action" class="form-control" placeholder="مثال: product أو invoice" value="{{ request('action') }}"></div><div class="col-lg-2"><label class="form-label small text-muted">التاريخ من</label><input name="date_from" type="date" class="form-control" value="{{ request('date_from') }}"></div><div class="col-lg-2"><label class="form-label small text-muted">التاريخ إلى</label><input name="date_to" type="date" class="form-control" value="{{ request('date_to') }}"></div><div class="col-lg-2"><button class="btn btn-primary w-100">🔎 تصفية</button></div></div></form>
@if($activities->isEmpty())
    <div class="empty-state" dir="rtl"><div class="empty-state-icon mb-3">📝</div><h2 class="h4">لا توجد نشاطات مطابقة</h2><p class="text-muted">غيّر الفلاتر أو جرّب نطاق تاريخ مختلف.</p></div>
@else
<div class="activity-card card" dir="rtl"><div class="activity-timeline">@foreach($activities as $activity)<div class="activity-item"><div class="activity-icon">{{ str_contains($activity->action, 'created') ? '➕' : (str_contains($activity->action, 'updated') ? '✏️' : (str_contains($activity->action, 'deactivated') ? '⏸️' : '📝')) }}</div><div><div class="d-flex flex-wrap gap-2 align-items-center justify-content-between"><div class="activity-action">{{ $activity->action }}</div><span class="activity-badge">{{ class_basename($activity->auditable_type) ?: 'System' }}</span></div><div class="activity-meta mt-2"><span>👤 {{ $activity->user?->name ?: 'النظام' }}</span><span class="mx-2">•</span><span>🕒 {{ $activity->created_at?->format('Y-m-d H:i') }}</span>@if($activity->auditable_id)<span class="mx-2">•</span><span>مرجع #{{ $activity->auditable_id }}</span>@endif</div></div></div>@endforeach</div></div><div class="mt-3">{{ $activities->links() }}</div>
@endif
@endsection
