@extends('layouts.guest')
@section('title', 'المدونة | أخبار الفوترة الإلكترونية الأردنية من InvoSync')
@push('styles')<link rel="stylesheet" href="{{ asset('css/blog.css') }}">@endpush
@section('content')
<section class="blog-hero"><div class="container"><span class="hbadge mb-3 d-inline-flex"><span class="bdot"></span>المدونة</span><h1 class="display-5 fw-bold mb-3">أخبار ودلائل الفوترة الإلكترونية في الأردن</h1><p class="lead" style="color:var(--tx2);max-width:760px">محتوى عملي يساعد المنشآت على فهم نظام الفوترة الوطني الأردني، متطلبات JoFotara، وكيفية تشغيل الربط بثقة عبر InvoSync.</p></div></section>
<section class="py-5"><div class="container">
<form class="blog-filter mb-4 row g-3 align-items-end" method="get"><div class="col-md-6"><label class="form-label">بحث</label><input class="form-control" name="q" value="{{ request('q') }}" placeholder="ابحث في المقالات"></div><div class="col-md-4"><label class="form-label">التصنيف</label><select class="form-select" name="category"><option value="">كل التصنيفات</option>@foreach($categories as $category)<option value="{{ $category }}" @selected(request('category')===$category)>{{ $category }}</option>@endforeach</select></div><div class="col-md-2 d-grid"><button class="bgrd btn">تصفية</button></div></form>
@if($featured && !request()->filled('q') && !request()->filled('category'))<div class="row g-4 align-items-center mb-5"><div class="col-lg-6"><img class="blog-img rounded-4" style="height:340px" src="{{ $featured->image_url }}" alt="{{ $featured->title_ar }}"></div><div class="col-lg-6"><span class="blog-pill">{{ $featured->category }}</span><h2 class="fw-bold my-3">{{ $featured->title_ar }}</h2><p style="color:var(--tx2);line-height:1.8">{{ $featured->excerpt_ar }}</p><a class="bgrd btn rounded-pill px-4" href="{{ route('blogs.show',$featured->slug) }}">اقرأ المزيد</a></div></div>@endif
<div class="row g-4">@forelse($posts as $post)<div class="col-md-6 col-lg-4"><article class="blog-card"><img class="blog-img" src="{{ $post->image_url }}" alt="{{ $post->title_ar }}"><div class="p-4"><div class="d-flex justify-content-between gap-2 mb-3"><span class="blog-pill">{{ $post->category ?: 'InvoSync' }}</span><span class="blog-meta">{{ $post->published_at?->format('Y-m-d') }}</span></div><h2 class="h5 fw-bold">{{ $post->title_ar }}</h2><p style="color:var(--tx2);line-height:1.7">{{ $post->excerpt_ar }}</p><a class="btn boc rounded-pill" href="{{ route('blogs.show',$post->slug) }}">اقرأ المزيد</a></div></article></div>@empty<div class="col-12 text-center py-5 text-muted">لا توجد مقالات مطابقة.</div>@endforelse</div><div class="mt-4">{{ $posts->links() }}</div>
</div></section>
@endsection
