@extends('layouts.app')
@section('title', 'الوحدات')
@section('content')
@php($routeCompanyId = $company->id ?? request()->route('company')?->id ?? request()->route('company') ?? auth()->user()?->company_id)
<div class="master-hero d-flex flex-column flex-lg-row align-items-lg-center justify-content-between gap-3" dir="rtl">
    <div class="d-flex gap-3 align-items-center"><div class="master-icon bg-white text-info">📏</div><div><h1 class="h3 mb-2">الوحدات</h1><p class="mb-0 opacity-75">استخدم الوحدات لتحديد طريقة قياس المنتجات والخدمات.</p></div></div>
    <a class="btn btn-light btn-lg" href="{{ route('company.units.create', ['company' => $routeCompanyId]) }}">➕ إضافة وحدة جديدة</a>
</div>
<form class="master-filter card card-body mb-3" dir="rtl"><div class="row g-2 align-items-end"><div class="col-lg-7"><label class="form-label small text-muted">بحث</label><input name="search" class="form-control" placeholder="ابحث بالاسم أو الرمز أو الكود" value="{{ request('search') }}"></div><div class="col-lg-3"><label class="form-label small text-muted">الحالة</label><select name="status" class="form-select"><option value="">كل الحالات</option><option value="active" @selected(request('status')==='active')>نشطة</option><option value="inactive" @selected(request('status')==='inactive')>غير نشطة</option></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">🔎 تصفية</button></div></div></form>
@if($units->isEmpty())
    <div class="empty-state" dir="rtl"><div class="empty-state-icon mb-3">📏</div><h2 class="h4">لا توجد وحدات بعد</h2><p class="text-muted">أضف وحدة قياس لاستخدامها عند تعريف المنتجات والخدمات.</p><a class="btn btn-primary" href="{{ route('company.units.create', ['company' => $routeCompanyId]) }}">➕ إضافة أول وحدة</a></div>
@else
<div class="master-table-card card overflow-hidden" dir="rtl"><div class="table-responsive"><table class="table master-table mb-0 align-middle"><thead><tr><th>الأيقونة</th><th>الاسم</th><th>الرمز</th><th>الكود</th><th>النوع</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>@foreach($units as $unit)<tr><td><span class="master-icon">📏</span></td><td><strong>{{ $unit->name_ar ?: $unit->name }}</strong><div class="text-muted small">{{ $unit->name_en ?: '—' }}</div></td><td>{{ $unit->symbol ?: '—' }}</td><td><code>{{ $unit->code }}</code></td><td><span class="type-badge {{ $unit->company_id ? '' : 'global' }}">{{ $unit->company_id ? 'خاصة بالمنشأة' : 'عامة' }}</span></td><td><span class="status-badge {{ $unit->is_active ? '' : 'inactive' }}">{{ $unit->is_active ? 'نشطة' : 'غير نشطة' }}</span></td><td><div class="d-flex flex-wrap gap-1"><a class="btn btn-sm btn-outline-primary action-btn" href="{{ route('company.units.edit', ['company' => $routeCompanyId, 'unit' => $unit->id]) }}">تعديل</a>@if($unit->company_id)<form method="post" action="{{ $unit->is_active ? route('company.units.deactivate', ['company' => $routeCompanyId, 'unit' => $unit->id]) : route('company.units.activate', ['company' => $routeCompanyId, 'unit' => $unit->id]) }}">@csrf<button class="btn btn-sm {{ $unit->is_active ? 'btn-outline-warning' : 'btn-outline-success' }} action-btn">{{ $unit->is_active ? 'تعطيل' : 'تفعيل' }}</button></form>@endif</div></td></tr>@endforeach</tbody></table></div></div><div class="mt-3">{{ $units->links() }}</div>
@endif
@endsection
