@extends('layouts.app')
@section('title', 'طلبات الاشتراك')
@push('styles')<link rel="stylesheet" href="{{ asset('css/subscription-requests.css') }}">@endpush
@section('content')
<div dir="rtl">
    <div class="subscription-request-hero mb-4"><span class="badge bg-white text-primary mb-2">Super Admin</span><h1 class="h3 mb-2">طلبات الاشتراك من الزوار</h1><p class="mb-0 opacity-75">راجع الطلبات، تواصل مع العملاء، ثم غيّر الحالة عند القبول أو الرفض.</p></div>
    <div class="subscription-request-admin-card p-4 mb-4"><form method="get" class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label">الحالة</label><select name="status" class="form-select"><option value="">كل الحالات</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">الباقة</label><select name="plan_id" class="form-select"><option value="">كل الباقات</option>@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected((string)request('plan_id')===(string)$plan->id)>{{ $plan->name_ar ?: $plan->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">مدة الاشتراك</label><select name="billing_cycle" class="form-select"><option value="">الكل</option><option value="monthly" @selected(request('billing_cycle')==='monthly')>monthly</option><option value="yearly" @selected(request('billing_cycle')==='yearly')>yearly</option></select></div><div class="col-md-3 d-grid"><button class="btn btn-outline-primary rounded-pill">تصفية</button></div></form></div>
    <div class="subscription-request-admin-card p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>الشركة</th><th>مقدم الطلب</th><th>التواصل</th><th>الباقة</th><th>المدة</th><th>الحالة</th><th>التاريخ</th><th></th></tr></thead><tbody>@forelse($requests as $request)<tr><td class="fw-bold">{{ $request->company_name }}</td><td>{{ $request->applicant_name }}</td><td><div>{{ $request->email }}</div><small class="text-muted">{{ $request->phone }}</small></td><td>{{ $request->plan?->name_ar ?: $request->plan?->name }}</td><td>{{ $request->billing_cycle }}</td><td><span class="badge bg-info text-dark">{{ $request->status }}</span></td><td>{{ $request->created_at?->format('Y-m-d H:i') }}</td><td><a class="btn btn-sm btn-primary rounded-pill" href="{{ route('admin.subscription-requests.show', $request) }}">تفاصيل</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">لا توجد طلبات اشتراك.</td></tr>@endforelse</tbody></table></div>{{ $requests->links() }}</div>
</div>
@endsection
