@extends('layouts.app')
@section('title', 'تفاصيل طلب الاشتراك')
@push('styles')<link rel="stylesheet" href="{{ asset('css/subscription-requests.css') }}">@endpush
@section('content')
<div dir="rtl">
    <div class="subscription-request-hero mb-4"><span class="badge bg-white text-primary mb-2">طلب #{{ $subscriptionRequest->id }}</span><h1 class="h3 mb-2">{{ $subscriptionRequest->company_name }}</h1><p class="mb-0 opacity-75">اقبل الطلب أولًا، ثم استخدم تجهيز الاشتراك لإنشاء المنشأة والمستخدم والاشتراك من نموذج قابل للمراجعة.</p></div>
    @if($subscriptionRequest->isProvisioned())<div class="subscription-request-admin-card p-4 mb-4"><h2 class="h5 fw-bold mb-3">نتيجة التجهيز</h2><div class="row g-3"><div class="col-md-6"><strong>المنشأة:</strong> <a href="{{ route('admin.companies.show', $subscriptionRequest->company) }}">{{ $subscriptionRequest->company?->name_ar ?: $subscriptionRequest->company?->legal_name_ar }}</a></div><div class="col-md-6"><strong>المستخدم الرئيسي:</strong> {{ $subscriptionRequest->user?->name }} — {{ $subscriptionRequest->user?->email }}</div><div class="col-md-6"><strong>الباقة:</strong> {{ $subscriptionRequest->subscription?->plan?->name_ar ?: $subscriptionRequest->subscription?->plan?->name }}</div><div class="col-md-6"><strong>الاشتراك:</strong> #{{ $subscriptionRequest->subscription?->id }} / {{ $subscriptionRequest->subscription?->billing_cycle }}</div><div class="col-md-6"><strong>البداية:</strong> {{ $subscriptionRequest->subscription?->current_period_start_at?->format('Y-m-d') ?: $subscriptionRequest->subscription?->starts_at?->format('Y-m-d') }}</div><div class="col-md-6"><strong>النهاية:</strong> {{ $subscriptionRequest->subscription?->current_period_end_at?->format('Y-m-d') ?: $subscriptionRequest->subscription?->expires_at?->format('Y-m-d') }}</div><div class="col-12"><a class="btn btn-primary rounded-pill" href="{{ route('admin.companies.show', $subscriptionRequest->company) }}">فتح المنشأة</a> <a class="btn btn-outline-primary rounded-pill" href="{{ route('admin.companies.subscriptions.index', $subscriptionRequest->company) }}">فتح الاشتراك</a></div></div></div>@endif
    <div class="row g-4"><div class="col-lg-7"><div class="subscription-request-admin-card p-4"><h2 class="h5 fw-bold mb-3">بيانات الطلب</h2><dl class="row mb-0"><dt class="col-sm-4">مقدم الطلب</dt><dd class="col-sm-8">{{ $subscriptionRequest->applicant_name }}</dd><dt class="col-sm-4">البريد</dt><dd class="col-sm-8">{{ $subscriptionRequest->email }}</dd><dt class="col-sm-4">الهاتف</dt><dd class="col-sm-8">{{ $subscriptionRequest->phone }}</dd><dt class="col-sm-4">واتساب</dt><dd class="col-sm-8">{{ $subscriptionRequest->whatsapp ?: '—' }}</dd><dt class="col-sm-4">الباقة</dt><dd class="col-sm-8">{{ $subscriptionRequest->plan?->name_ar ?: $subscriptionRequest->plan?->name }}</dd><dt class="col-sm-4">مدة الاشتراك</dt><dd class="col-sm-8">{{ $subscriptionRequest->billing_cycle }}</dd><dt class="col-sm-4">الحالة</dt><dd class="col-sm-8">{{ $subscriptionRequest->status }}</dd><dt class="col-sm-4">ملاحظات العميل</dt><dd class="col-sm-8">{{ $subscriptionRequest->notes ?: '—' }}</dd><dt class="col-sm-4">اعتمد بواسطة</dt><dd class="col-sm-8">{{ $subscriptionRequest->approvedBy?->name ?: '—' }} @if($subscriptionRequest->approved_at) / {{ $subscriptionRequest->approved_at->format('Y-m-d H:i') }} @endif</dd><dt class="col-sm-4">تم التجهيز بواسطة</dt><dd class="col-sm-8">{{ $subscriptionRequest->provisionedBy?->name ?: '—' }} @if($subscriptionRequest->provisioned_at) / {{ $subscriptionRequest->provisioned_at->format('Y-m-d H:i') }} @endif</dd></dl></div></div><div class="col-lg-5"><form method="post" action="{{ route('admin.subscription-requests.update', $subscriptionRequest) }}" class="subscription-request-admin-card p-4">@csrf @method('PUT')<h2 class="h5 fw-bold mb-3">إدارة الطلب</h2><label class="form-label">ملاحظات داخلية</label><textarea name="admin_notes" class="form-control mb-3" rows="5">{{ old('admin_notes', $subscriptionRequest->admin_notes) }}</textarea><div class="d-flex flex-wrap gap-2"><button class="btn btn-outline-info rounded-pill px-4" name="status" value="contacted" @disabled($subscriptionRequest->isProvisioned())>تم التواصل</button><button class="btn btn-primary rounded-pill px-4" name="status" value="approved" @disabled($subscriptionRequest->isProvisioned())>قبول الطلب</button><button class="btn btn-outline-danger rounded-pill px-4" name="status" value="rejected" @disabled($subscriptionRequest->isProvisioned())>رفض الطلب</button></div>@if(! $subscriptionRequest->isProvisioned() && in_array($subscriptionRequest->status, ['approved','contacted','pending'], true))<a class="btn btn-outline-success rounded-pill px-4 mt-3" href="{{ route('admin.subscription-requests.provision.create', $subscriptionRequest) }}">تجهيز الاشتراك</a>@endif</form></div></div>
</div>
@endsection
