@extends('layouts.app')
@section('title', 'تفاصيل طلب الاشتراك')
@push('styles')<link rel="stylesheet" href="{{ asset('css/subscription-requests.css') }}">@endpush
@section('content')
<div dir="rtl">
    <div class="subscription-request-hero mb-4"><span class="badge bg-white text-primary mb-2">طلب #{{ $subscriptionRequest->id }}</span><h1 class="h3 mb-2">{{ $subscriptionRequest->company_name }}</h1><p class="mb-0 opacity-75">استخدم زر تجهيز الاشتراك كإجراء واضح بعد اعتماد الطلب يدويًا.</p></div>
    <div class="row g-4"><div class="col-lg-7"><div class="subscription-request-admin-card p-4"><h2 class="h5 fw-bold mb-3">بيانات الطلب</h2><dl class="row mb-0"><dt class="col-sm-4">مقدم الطلب</dt><dd class="col-sm-8">{{ $subscriptionRequest->applicant_name }}</dd><dt class="col-sm-4">البريد</dt><dd class="col-sm-8">{{ $subscriptionRequest->email }}</dd><dt class="col-sm-4">الهاتف</dt><dd class="col-sm-8">{{ $subscriptionRequest->phone }}</dd><dt class="col-sm-4">واتساب</dt><dd class="col-sm-8">{{ $subscriptionRequest->whatsapp ?: '—' }}</dd><dt class="col-sm-4">الباقة</dt><dd class="col-sm-8">{{ $subscriptionRequest->plan?->name_ar ?: $subscriptionRequest->plan?->name }}</dd><dt class="col-sm-4">مدة الاشتراك</dt><dd class="col-sm-8">{{ $subscriptionRequest->billing_cycle }}</dd><dt class="col-sm-4">الحالة</dt><dd class="col-sm-8">{{ $subscriptionRequest->status }}</dd><dt class="col-sm-4">ملاحظات العميل</dt><dd class="col-sm-8">{{ $subscriptionRequest->notes ?: '—' }}</dd><dt class="col-sm-4">اعتمد بواسطة</dt><dd class="col-sm-8">{{ $subscriptionRequest->approvedBy?->name ?: '—' }} @if($subscriptionRequest->approved_at) / {{ $subscriptionRequest->approved_at->format('Y-m-d H:i') }} @endif</dd></dl></div></div><div class="col-lg-5"><form method="post" action="{{ route('admin.subscription-requests.update', $subscriptionRequest) }}" class="subscription-request-admin-card p-4">@csrf @method('PUT')<h2 class="h5 fw-bold mb-3">إدارة الطلب</h2><label class="form-label">الحالة</label><select name="status" class="form-select mb-3"><option value="pending" @selected($subscriptionRequest->status==='pending')>pending</option><option value="contacted" @selected($subscriptionRequest->status==='contacted')>contacted</option><option value="approved" @selected($subscriptionRequest->status==='approved')>approved</option><option value="rejected" @selected($subscriptionRequest->status==='rejected')>rejected</option></select><label class="form-label">ملاحظات داخلية</label><textarea name="admin_notes" class="form-control mb-3" rows="6">{{ old('admin_notes', $subscriptionRequest->admin_notes) }}</textarea><button class="btn btn-primary rounded-pill px-4">حفظ التحديث</button><button class="btn btn-outline-success rounded-pill px-4" name="status" value="approved">تجهيز الاشتراك</button><p class="text-muted small mt-3 mb-0">TODO: سيتم ربط إجراء تجهيز الاشتراك لاحقًا بخدمة إنشاء Company / Tenant + User + Subscription عند اكتمال البنية الآلية.</p></form></div></div>
</div>
@endsection
