@extends('layouts.app')
@section('title', 'العملاء والموردون')
@section('content')
@php($routeCompanyId = $company->id ?? request()->route('company')?->id ?? request()->route('company') ?? auth()->user()?->company_id)
<style>.contact-hero{background:linear-gradient(135deg,#00a9c4,#12c2b2);color:#fff;border-radius:24px;padding:24px;margin-bottom:18px;box-shadow:0 18px 42px rgba(15,23,42,.12)}.contact-hero .btn{border-radius:999px;font-weight:800}.contact-filter,.contact-table-card{border:1px solid #e5eef4;border-radius:22px;box-shadow:0 12px 30px rgba(15,23,42,.06)}.contact-filter .form-control,.contact-filter .form-select{border-radius:14px}.contact-avatar{width:48px;height:48px;border-radius:16px;background:#eefcff;display:inline-grid;place-items:center;font-size:1.1rem;border:1px solid #d7eef3;color:#0f6170;font-weight:800}.contact-table th{background:#f7fbfc;color:#475569;white-space:nowrap}.contact-table td{vertical-align:middle}.status-badge,.type-badge{display:inline-flex;border-radius:999px;padding:5px 10px;font-size:.8rem;border:1px solid #d7eef3;background:#f1f9fb;color:#0f6170}.status-badge.inactive{background:#fff1f2;color:#9f1239;border-color:#fecdd3}.type-badge.supplier{background:#fff8e6;color:#7a5200;border-color:#ffe2a8}.type-badge.both{background:#f5f3ff;color:#5b21b6;border-color:#ddd6fe}.action-btn{border-radius:999px;min-width:78px}.empty-state{border:1px dashed #b7dce5;border-radius:22px;padding:42px;background:#f8fdff;text-align:center}.empty-state-icon{font-size:3rem}</style>
<div class="contact-hero d-flex flex-column flex-lg-row align-items-lg-center justify-content-between gap-3" dir="rtl"><div class="d-flex gap-3 align-items-center"><div class="contact-avatar bg-white text-info">🤝</div><div><h1 class="h3 mb-2">العملاء والموردون</h1><p class="mb-0 opacity-75">أدر بيانات العملاء والموردين لاستخدامها في الفواتير.</p></div></div><a class="btn btn-light btn-lg" href="{{ route('company.contacts.create', ['company' => $routeCompanyId]) }}">➕ إضافة عميل / مورد جديد</a></div>
<form class="contact-filter card card-body mb-3" dir="rtl"><div class="row g-2 align-items-end"><div class="col-lg-3"><label class="form-label small text-muted">الاسم</label><input name="search" class="form-control" placeholder="ابحث بالاسم أو الهاتف أو البريد" value="{{ request('search') }}"></div><div class="col-lg-3"><label class="form-label small text-muted">الرقم الضريبي/الوطني</label><input name="tax_number" class="form-control" placeholder="ابحث برقم ضريبي أو وطني" value="{{ request('tax_number') }}"></div><div class="col-lg-2"><label class="form-label small text-muted">النوع</label><select name="type" class="form-select"><option value="">كل الأنواع</option><option value="customer" @selected(request('type')==='customer')>عميل</option><option value="supplier" @selected(request('type')==='supplier')>مورد</option><option value="both" @selected(request('type')==='both')>كلاهما</option></select></div><div class="col-lg-2"><label class="form-label small text-muted">الحالة</label><select name="status" class="form-select"><option value="">كل الحالات</option><option value="active" @selected(request('status')==='active')>نشط</option><option value="inactive" @selected(request('status')==='inactive')>غير نشط</option></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">🔎 تصفية</button></div></div></form>
@if($contacts->isEmpty())
    <div class="empty-state" dir="rtl"><div class="empty-state-icon mb-3">🤝</div><h2 class="h4">لا توجد جهات اتصال بعد</h2><p class="text-muted">ابدأ بإضافة عميل أو مورد لاستخدامه عند إنشاء الفواتير.</p><a class="btn btn-primary" href="{{ route('company.contacts.create', ['company' => $routeCompanyId]) }}">➕ إضافة أول عميل / مورد</a></div>
@else
<div class="contact-table-card card overflow-hidden" dir="rtl"><div class="table-responsive"><table class="table contact-table mb-0 align-middle"><thead><tr><th>الاسم</th><th>النوع</th><th>الرقم الضريبي</th><th>الهاتف</th><th>البريد</th><th>المدينة</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>@foreach($contacts as $contact)<tr><td><div class="d-flex align-items-center gap-2"><span class="contact-avatar">{{ mb_substr($contact->name_ar, 0, 1) }}</span><div><strong>{{ $contact->name_ar }}</strong><div class="text-muted small">{{ $contact->name_en ?: '—' }}</div></div></div></td><td><span class="type-badge {{ $contact->type }}">{{ $contact->type === 'supplier' ? 'مورد' : ($contact->type === 'both' ? 'عميل ومورد' : 'عميل') }}</span></td><td>{{ $contact->tax_number ?: $contact->national_number ?: '—' }}</td><td>{{ $contact->phone ?: '—' }}</td><td>{{ $contact->email ?: '—' }}</td><td>{{ $contact->city ?: '—' }}</td><td><span class="status-badge {{ $contact->is_active ? '' : 'inactive' }}">{{ $contact->is_active ? 'نشط' : 'غير نشط' }}</span></td><td><div class="d-flex flex-wrap gap-1"><a class="btn btn-sm btn-outline-primary action-btn" href="{{ route('company.contacts.edit', ['company' => $routeCompanyId, 'contact' => $contact->id]) }}">تعديل</a><form method="post" action="{{ $contact->is_active ? route('company.contacts.deactivate', ['company' => $routeCompanyId, 'contact' => $contact->id]) : route('company.contacts.activate', ['company' => $routeCompanyId, 'contact' => $contact->id]) }}">@csrf<button class="btn btn-sm {{ $contact->is_active ? 'btn-outline-warning' : 'btn-outline-success' }} action-btn">{{ $contact->is_active ? 'تعطيل' : 'تفعيل' }}</button></form></div></td></tr>@endforeach</tbody></table></div></div><div class="mt-3">{{ $contacts->links() }}</div>
@endif
@endsection
