@extends('layouts.app')
@section('title', 'إعدادات الضرائب')
@section('content')
@php($routeCompanyId = $company->id ?? request()->route('company')?->id ?? request()->route('company') ?? auth()->user()?->company_id)
<style>.tax-hero{background:linear-gradient(135deg,#00a9c4,#12c2b2);color:#fff;border-radius:24px;padding:24px;margin-bottom:18px;box-shadow:0 18px 42px rgba(15,23,42,.12)}.tax-hero .btn{border-radius:999px;font-weight:800}.tax-filter,.tax-table-card{border:1px solid #e5eef4;border-radius:22px;box-shadow:0 12px 30px rgba(15,23,42,.06)}.tax-filter .form-control,.tax-filter .form-select{border-radius:14px}.tax-icon{width:48px;height:48px;border-radius:16px;background:#eefcff;display:inline-grid;place-items:center;font-size:1.35rem;border:1px solid #d7eef3}.tax-table th{background:#f7fbfc;color:#475569;white-space:nowrap}.tax-table td{vertical-align:middle}.status-badge,.default-badge{display:inline-flex;border-radius:999px;padding:5px 10px;font-size:.8rem;border:1px solid #d7eef3;background:#f1f9fb;color:#0f6170}.status-badge.inactive{background:#fff1f2;color:#9f1239;border-color:#fecdd3}.default-badge.no{background:#f8fafc;color:#64748b;border-color:#e2e8f0}.action-btn{border-radius:999px;min-width:78px}.empty-state{border:1px dashed #b7dce5;border-radius:22px;padding:42px;background:#f8fdff;text-align:center}.empty-state-icon{font-size:3rem}</style>
<div class="tax-hero d-flex flex-column flex-lg-row align-items-lg-center justify-content-between gap-3" dir="rtl"><div class="d-flex gap-3 align-items-center"><div class="tax-icon bg-white text-info">🧮</div><div><h1 class="h3 mb-2">إعدادات الضرائب</h1><p class="mb-0 opacity-75">حدد نسب وأنواع الضرائب المستخدمة في الفواتير.</p></div></div><a class="btn btn-light btn-lg" href="{{ route('company.tax-profiles.create', ['company' => $routeCompanyId]) }}">➕ إضافة ضريبة جديدة</a></div>
<form class="tax-filter card card-body mb-3" dir="rtl"><div class="row g-2 align-items-end"><div class="col-lg-7"><label class="form-label small text-muted">بحث</label><input name="search" class="form-control" placeholder="ابحث بالاسم أو النوع أو كود جوفوتارا" value="{{ request('search') }}"></div><div class="col-lg-3"><label class="form-label small text-muted">الحالة</label><select name="status" class="form-select"><option value="">كل الحالات</option><option value="active" @selected(request('status')==='active')>نشطة</option><option value="inactive" @selected(request('status')==='inactive')>غير نشطة</option></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">🔎 تصفية</button></div></div></form>
@if($taxProfiles->isEmpty())
    <div class="empty-state" dir="rtl"><div class="empty-state-icon mb-3">🧮</div><h2 class="h4">لا توجد إعدادات ضرائب بعد</h2><p class="text-muted">أضف ضريبة جديدة لاستخدامها مع المنتجات والفواتير.</p><a class="btn btn-primary" href="{{ route('company.tax-profiles.create', ['company' => $routeCompanyId]) }}">➕ إضافة أول ضريبة</a></div>
@else
<div class="tax-table-card card overflow-hidden" dir="rtl"><div class="table-responsive"><table class="table tax-table mb-0 align-middle"><thead><tr><th>الأيقونة</th><th>الاسم</th><th>النوع</th><th>النسبة</th><th>كود جوفوتارا</th><th>الافتراضية</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>@foreach($taxProfiles as $taxProfile)<tr><td><span class="tax-icon">🧮</span></td><td><strong>{{ $taxProfile->name }}</strong></td><td>{{ $taxProfile->tax_type }}</td><td><strong>{{ $taxProfile->tax_percent }}%</strong></td><td>{{ $taxProfile->jofotara_tax_code ?: '—' }}</td><td><span class="default-badge {{ $taxProfile->is_default ? '' : 'no' }}">{{ $taxProfile->is_default ? 'افتراضية' : 'غير افتراضية' }}</span></td><td><span class="status-badge {{ $taxProfile->is_active ? '' : 'inactive' }}">{{ $taxProfile->is_active ? 'نشطة' : 'غير نشطة' }}</span></td><td><div class="d-flex flex-wrap gap-1">@if($taxProfile->company_id)<a class="btn btn-sm btn-outline-primary action-btn" href="{{ route('company.tax-profiles.edit', ['company' => $routeCompanyId, 'tax_profile' => $taxProfile->id]) }}">تعديل</a><form method="post" action="{{ $taxProfile->is_active ? route('company.tax-profiles.deactivate', ['company' => $routeCompanyId, 'tax_profile' => $taxProfile->id]) : route('company.tax-profiles.activate', ['company' => $routeCompanyId, 'tax_profile' => $taxProfile->id]) }}">@csrf<button class="btn btn-sm {{ $taxProfile->is_active ? 'btn-outline-warning' : 'btn-outline-success' }} action-btn">{{ $taxProfile->is_active ? 'تعطيل' : 'تفعيل' }}</button></form>@else<span class="text-muted small">عام</span>@endif</div></td></tr>@endforeach</tbody></table></div></div><div class="mt-3">{{ $taxProfiles->links() }}</div>
@endif
@endsection
