@php($variant = $variant ?? 'classic')
<!doctype html>
<html lang="{{ str_contains($data->language, 'en') ? 'en' : 'ar' }}" dir="{{ $data->direction }}">
<head><meta charset="utf-8"><title>{{ $data->invoice->invoice_number }}</title>
</head><body class="{{ $variant }}"><main class="sheet">
<section class="{{ in_array($variant,['modern','bilingual'])?'hero':'' }} top"><div class="brand">@if($data->branding['logo'])<img class="logo" src="{{ asset($data->branding['logo']) }}" alt="logo">@else<div class="logo-ph">{{ $data->branding['initials'] }}</div>@endif<div><h1>{{ $data->company->name_ar ?: $data->company->legal_name_ar ?: $data->company->name_en }}</h1><div class="muted">{{ $data->company->tax_number }} · {{ $data->company->jofotara_source_id ?: 'لا يوجد مصدر' }}</div><div class="muted">{{ $data->company->phone }} {{ $data->company->email ? ' · '.$data->company->email : '' }}</div><div class="muted">{{ trim(($data->company->city ?: '').' '.($data->company->street ?: '').' '.($data->company->building_no ?: '')) }}</div></div></div><div><h2>{{ $variant==='receipt'?'إيصال بيع':'فاتورة ضريبية' }}</h2><div>{{ $data->invoice->invoice_number }}</div><span class="badge">{{ $data->invoice->status }}</span> <span class="badge">JoFotara: {{ $data->jofotara['status'] ?: 'غير مرسلة' }}</span></div></section>
<section class="grid"><div class="card"><h3>البائع / Seller</h3><p>{{ $data->company->legal_name_ar ?: $data->company->name_ar }}</p><p class="muted">Tax No: {{ $data->company->tax_number }}</p></div><div class="card"><h3>المشتري / Customer</h3><p>{{ $data->customer?->name_ar ?: $data->customer?->name_en ?: 'عميل نقدي' }}</p><p class="muted">{{ $data->customer?->tax_number ?: $data->customer?->national_number ?: '—' }}</p></div><div class="card"><h3>بيانات الفاتورة</h3><p>تاريخ الإصدار: {{ optional($data->invoice->issue_date)->format('Y-m-d') ?: $data->invoice->issue_date }}</p><p>تاريخ الاستحقاق: {{ optional($data->invoice->due_date)->format('Y-m-d') ?: '—' }}</p><p>UUID: {{ $data->jofotara['uuid'] ?: '—' }}</p></div><div class="card"><h3>QR</h3><div class="qrbox">@if($data->qr['data_uri'])<img src="{{ $data->qr['data_uri'] }}" alt="JoFotara QR"><small class="muted break-all">{{ $data->qr['value'] }}</small>@else<div class="qr-placeholder">{{ $data->qr['placeholder'] }}</div>@endif</div></div></section>
<table><thead><tr><th>#</th><th>الوصف<br><span class="ltr">Description</span></th><th>الكمية</th><th>السعر</th><th>الخصم</th><th>الضريبة</th><th>الإجمالي</th></tr></thead><tbody>@forelse($data->items as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->description }}</td><td>{{ $item->quantity }}</td><td>{{ $item->unit_price }}</td><td>{{ $item->discount_amount }}</td><td>{{ $item->tax_amount }}</td><td>{{ $item->line_total }}</td></tr>@empty<tr><td colspan="7">لا توجد بنود</td></tr>@endforelse</tbody></table>
<table class="totals"><tr><th>المجموع الفرعي</th><td>{{ $data->totals['subtotal'] }} {{ $data->totals['currency'] }}</td></tr><tr><th>الخصم</th><td>{{ $data->totals['discount'] }} {{ $data->totals['currency'] }}</td></tr><tr><th>ضريبة المبيعات</th><td>{{ $data->totals['tax'] }} {{ $data->totals['currency'] }}</td></tr><tr class="total-grand"><th>الإجمالي</th><td>{{ $data->totals['grand'] }} {{ $data->totals['currency'] }}</td></tr></table>
<section class="grid hide-receipt"><div class="card"><h3>ملاحظات</h3><p>{{ $data->invoice->notes ?: '—' }}</p><h3>الشروط والأحكام</h3><p>{{ $data->branding['terms_and_conditions'] }}</p></div><div class="card sign"><strong>{{ $data->branding['signature_block'] }}</strong><br>@if($data->branding['stamp_image'])<img class="stamp" src="{{ asset($data->branding['stamp_image']) }}" alt="stamp">@endif</div></section>
<footer class="footer muted">{{ $data->branding['footer_text'] }}</footer>
</main></body></html>
