@extends('layouts.company-workspace')
@section('title', 'إعدادات المنشأة')
@section('content')
@php($routeCompanyId = $company->id ?? request()->route('company')?->id ?? request()->route('company') ?? auth()->user()?->company_id)
@php($value = fn(string $key, ?string $fallback = '') => old('settings.'.$key, $settings[$key]->value ?? $fallback))
<div class="settings-hero" dir="rtl"><h1 class="h3 mb-2">إعدادات المنشأة</h1><p class="mb-0 opacity-75">إدارة بيانات الهوية، الفواتير، اللغة، العملة، وحالة الربط مع جوفوتارا.</p></div>
<form method="post" action="{{ route('company.settings.update', ['company' => $routeCompanyId]) }}" enctype="multipart/form-data" class="settings-card" data-settings-form dir="rtl">
    @csrf @method('PUT')
    <div class="settings-tabs" role="tablist"><button type="button" class="settings-tab active" data-tab="general">بيانات عامة</button><button type="button" class="settings-tab" data-tab="branding">الهوية البصرية</button><button type="button" class="settings-tab" data-tab="invoice">إعدادات الفواتير</button><button type="button" class="settings-tab" data-tab="jofotara">إعدادات جوفوتارا</button><button type="button" class="settings-tab" data-tab="locale">اللغة والعملة</button></div>
    <div class="settings-panel active" data-panel="general"><div class="alert alert-danger validation-summary" data-validation-summary></div><div class="row g-3"><div class="col-md-6"><label class="form-label">اسم المنشأة</label><input class="form-control" value="{{ $company->name_ar ?: $company->legal_name_ar }}" placeholder="اسم المنشأة" disabled><div class="form-text">يتم تعديل البيانات القانونية من شاشة إدارة المنشأة.</div></div><div class="col-md-6"><label class="form-label">الرقم الضريبي</label><input class="form-control" value="{{ $company->tax_number }}" placeholder="الرقم الضريبي" disabled></div><div class="col-md-6"><label class="form-label">شعار المنشأة</label><div class="preview-box"><input type="hidden" name="settings[company_logo]" value="{{ $value('company_logo') }}"><input class="form-control" type="file" accept="image/*" name="company_logo_file" data-image-input data-preview="company-logo-preview"><div class="form-text mt-2">PNG/JPG/WEBP حتى 2MB.</div>@if($value('company_logo'))<img id="company-logo-preview" class="mt-2" src="{{ asset('storage/'.$value('company_logo')) }}" alt="شعار المنشأة">@else<img id="company-logo-preview" class="mt-2" src="{{ asset('assets/images/invoice-placeholder-logo.svg') }}" alt="شعار المنشأة">@endif</div></div><div class="col-md-6"><label class="form-label">نص تذييل عام</label><textarea class="form-control" rows="5" name="settings[invoice_footer_text]" placeholder="مثال: شكراً لتعاملكم معنا">{{ $value('invoice_footer_text') }}</textarea><div class="form-text">يظهر في قوالب الفواتير عند الحاجة.</div></div></div></div>
    <div class="settings-panel" data-panel="branding"><div class="row g-3"><div class="col-md-4"><label class="form-label">لون الهوية</label><input class="form-control form-control-color" type="color" name="settings[brand_color]" value="{{ $value('brand_color', '#00a9c4') ?: '#00a9c4' }}"><div class="form-text">اللون العام للمنشأة.</div></div><div class="col-md-4"><label class="form-label">لون الفاتورة الأساسي</label><input class="form-control form-control-color" type="color" name="settings[invoice_primary_color]" value="{{ $value('invoice_primary_color', '#00a9c4') ?: '#00a9c4' }}"></div><div class="col-md-4"><label class="form-label">لون الفاتورة الثانوي</label><input class="form-control form-control-color" type="color" name="settings[invoice_secondary_color]" value="{{ $value('invoice_secondary_color', '#12c2b2') ?: '#12c2b2' }}"></div><div class="col-md-6"><label class="form-label">شعار الفاتورة</label><div class="preview-box"><input type="hidden" name="settings[invoice_logo]" value="{{ $value('invoice_logo') }}"><input class="form-control" type="file" accept="image/*" name="invoice_logo_file" data-image-input data-preview="invoice-logo-preview"><div class="form-text mt-2">يستخدم في رأس الفاتورة.</div><img id="invoice-logo-preview" class="mt-2" src="{{ $value('invoice_logo') ? asset('storage/'.$value('invoice_logo')) : asset('assets/images/invoice-placeholder-logo.svg') }}" alt="شعار الفاتورة"></div></div><div class="col-md-6"><label class="form-label">صورة الختم</label><div class="preview-box"><input type="hidden" name="settings[invoice_stamp_image]" value="{{ $value('invoice_stamp_image') }}"><input class="form-control" type="file" accept="image/*" name="invoice_stamp_image_file" data-image-input data-preview="stamp-preview"><div class="form-text mt-2">اختياري ويظهر في منطقة التوقيع.</div><img id="stamp-preview" class="mt-2" src="{{ $value('invoice_stamp_image') ? asset('storage/'.$value('invoice_stamp_image')) : asset('assets/images/invoice-placeholder-logo.svg') }}" alt="ختم المنشأة"></div></div></div></div>
    <div class="settings-panel" data-panel="invoice"><div class="row g-3"><div class="col-md-6"><label class="form-label">قالب الفاتورة الافتراضي</label><input class="form-control" name="settings[invoice_template_id]" placeholder="مثال: arabic-classic أو رقم القالب" value="{{ $value('invoice_template_id') }}"><div class="form-text">يمكن أيضاً اختيار القالب من صفحة قوالب الفواتير.</div></div><div class="col-md-6"><label class="form-label">بادئة الفاتورة</label><input class="form-control" name="settings[invoice_prefix]" placeholder="مثال: INV" value="{{ $value('invoice_prefix', 'INV') }}"></div><div class="col-12"><label class="form-label">الشروط والأحكام</label><textarea class="form-control" rows="5" name="settings[invoice_terms_and_conditions]" placeholder="اكتب شروط الدفع والتسليم أو أي ملاحظات قانونية">{{ $value('invoice_terms_and_conditions') }}</textarea></div><div class="col-12"><label class="form-label">كتلة التوقيع</label><textarea class="form-control" rows="3" name="settings[invoice_signature_block]" placeholder="مثال: المدير المالي / الختم الرسمي">{{ $value('invoice_signature_block') }}</textarea></div></div></div>
    <div class="settings-panel" data-panel="jofotara"><div class="row g-3"><div class="col-md-6"><label class="form-label">وضع جوفوتارا</label><select class="form-select" name="settings[jofotara_mode]"><option value="sandbox" @selected($value('jofotara_mode', 'sandbox') === 'sandbox')>تجريبي</option><option value="production" @selected($value('jofotara_mode') === 'production')>إنتاجي</option></select><div class="form-text">هذا الخيار للعرض والإعدادات فقط ولا يغيّر منطق الإرسال.</div></div><div class="col-md-6"><label class="form-label">حالة بيانات الربط</label><div class="secret-status"><div>حالة بيانات الربط: <strong>{{ $company->hasJofotaraClientId() && $company->hasJofotaraSecretKey() && filled($company->jofotara_source_id) ? 'محفوظة ومكتملة' : 'غير مكتملة' }}</strong></div><small class="text-muted">لا يتم عرض أي معرفات أو مفاتيح سرية في هذه الصفحة.</small></div></div></div></div>
    <div class="settings-panel" data-panel="locale"><div class="row g-3"><div class="col-md-6"><label class="form-label">اللغة الافتراضية</label><select class="form-select" name="settings[default_language]" required><option value="ar" @selected($value('default_language', $company->default_language ?: 'ar') === 'ar')>العربية</option><option value="en" @selected($value('default_language') === 'en')>English</option></select></div><div class="col-md-6"><label class="form-label">العملة الافتراضية</label><input class="form-control" name="settings[default_currency]" maxlength="3" placeholder="JOD" value="{{ $value('default_currency', $company->default_currency ?: 'JOD') }}" required><div class="form-text">رمز العملة من 3 أحرف مثل JOD أو USD.</div></div></div></div>
    <div class="settings-actions d-flex flex-wrap gap-2"><button class="btn btn-primary">حفظ الإعدادات</button><a class="btn btn-outline-secondary" href="{{ route('company.dashboard', ['company' => $routeCompanyId]) }}">إلغاء</a></div>
</form>
@endsection
