@extends('layouts.company-workspace')
@section('title', 'إعدادات المنشأة')
@section('content')
@php($routeCompanyId = $company->id ?? request()->route('company')?->id ?? request()->route('company') ?? auth()->user()?->company_id)
@php($value = fn(string $key, ?string $fallback = '') => old('settings.'.$key, $settings[$key]->value ?? $fallback))
@php($selectedCurrency = strtoupper((string) $value('default_currency', $company->default_currency ?: 'JOD')))
@php($currencyOptions = collect($currencies ?? [])->whenEmpty(fn ($items) => $items->push((object) ['code' => 'JOD', 'name' => 'Jordanian Dinar'])->push((object) ['code' => 'USD', 'name' => 'US Dollar'])->push((object) ['code' => 'EUR', 'name' => 'Euro'])))
<style>
    .settings-hero{position:relative;overflow:hidden;background:linear-gradient(135deg,#063f52,#00a9c4 58%,#12c2b2);color:#fff;border-radius:28px;padding:28px;margin-bottom:18px;box-shadow:0 20px 50px rgba(15,23,42,.14)}
    .settings-hero:after{content:"";position:absolute;inset:auto -60px -80px auto;width:240px;height:240px;background:rgba(255,255,255,.14);border-radius:50%}.settings-hero>*{position:relative;z-index:1}.settings-hero .hero-chip{display:inline-flex;gap:8px;align-items:center;background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.28);border-radius:999px;padding:7px 12px;font-size:.85rem;margin-bottom:12px}
    .settings-card{border:1px solid #e5eef4;border-radius:26px;box-shadow:0 14px 36px rgba(15,23,42,.07);overflow:hidden;background:#fff}.settings-tabs{display:grid;grid-template-columns:repeat(5,minmax(140px,1fr));gap:10px;border-bottom:1px solid #e5eef4;background:#f8fbfc;padding:14px}.settings-tab{border:1px solid #dcecf1;background:#fff;border-radius:18px;padding:12px 14px;color:#0f6170;font-weight:800;text-align:right;transition:.18s ease}.settings-tab small{display:block;color:#7b8b95;font-weight:600;margin-top:2px}.settings-tab.active{background:linear-gradient(135deg,#00a9c4,#12c2b2);border-color:transparent;color:#fff;box-shadow:0 10px 24px rgba(0,169,196,.22)}.settings-tab.active small{color:rgba(255,255,255,.82)}
    .settings-panel{display:none;padding:24px;background:linear-gradient(180deg,#fff,#fbfdfe)}.settings-panel.active{display:block}.section-title{display:flex;align-items:center;gap:10px;margin-bottom:18px}.section-title .icon{display:grid;place-items:center;width:42px;height:42px;border-radius:14px;background:#e9fbfd;color:#008ba3;font-size:1.2rem}.section-title h2{font-size:1.15rem;margin:0;color:#153b49}.section-title p{margin:3px 0 0;color:#6b7b86;font-size:.9rem}.field-card{height:100%;border:1px solid #e7f0f4;border-radius:20px;background:#fff;padding:16px;box-shadow:0 8px 22px rgba(15,23,42,.04)}.field-card .form-label{font-weight:800;color:#183b49}.settings-panel .form-control,.settings-panel .form-select{border-radius:14px;border-color:#dcecf1;min-height:46px}.settings-panel textarea.form-control{min-height:auto}.settings-panel .form-control:focus,.settings-panel .form-select:focus{border-color:#00a9c4;box-shadow:0 0 0 .2rem rgba(0,169,196,.12)}.preview-box{border:1px dashed #b7dce5;border-radius:18px;background:#f8fdff;padding:14px;text-align:center}.preview-box img{max-height:96px;max-width:190px;object-fit:contain}.secret-status{border-radius:18px;background:#f8fdff;border:1px solid #d7eef3;padding:16px;height:100%}.currency-select-wrap{position:relative}.currency-select-wrap:before{content:"💱";position:absolute;inset-inline-start:14px;top:50%;transform:translateY(-50%);z-index:2}.currency-select-wrap .form-select{padding-inline-start:46px}.settings-actions{background:#f8fbfc;border-top:1px solid #e5eef4;padding:18px 22px}.settings-actions .btn{border-radius:999px;min-width:150px}.validation-summary{display:none;border-radius:14px}@media(max-width:991px){.settings-tabs{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:575px){.settings-tabs{grid-template-columns:1fr}.settings-panel{padding:18px}.settings-hero{padding:22px}}
</style>
<div class="settings-hero" dir="rtl">
    <span class="hero-chip">⚙️ مركز التحكم بالمنشأة</span>
    <h1 class="h3 mb-2">إعدادات المنشأة</h1>
    <p class="mb-0 opacity-75">تبويب واضح ومنظّم لإدارة بيانات الهوية، شكل الفاتورة، اللغة، العملة، وحالة الربط مع جوفوتارا.</p>
</div>
<form method="post" action="{{ route('company.settings.update', ['company' => $routeCompanyId]) }}" enctype="multipart/form-data" class="settings-card" data-settings-form dir="rtl">
    @csrf @method('PUT')
    <div class="settings-tabs" role="tablist" aria-label="تبويبات إعدادات المنشأة">
        <button type="button" class="settings-tab active" data-tab="general">🏢 بيانات عامة<small>معلومات وهوية أساسية</small></button>
        <button type="button" class="settings-tab" data-tab="branding">🎨 الهوية البصرية<small>ألوان وشعارات</small></button>
        <button type="button" class="settings-tab" data-tab="invoice">🧾 الفواتير<small>قالب ونصوص الفاتورة</small></button>
        <button type="button" class="settings-tab" data-tab="jofotara">🔗 جوفوتارا<small>وضع وحالة الربط</small></button>
        <button type="button" class="settings-tab" data-tab="locale">🌐 اللغة والعملة<small>تفضيلات التشغيل</small></button>
    </div>
    <div class="settings-panel active" data-panel="general">
        <div class="alert alert-danger validation-summary" data-validation-summary></div>
        <div class="section-title"><span class="icon">🏢</span><div><h2>بيانات المنشأة الأساسية</h2><p>حقول تعريفية سريعة مع شعار عام للمنشأة.</p></div></div>
        <div class="row g-3"><div class="col-lg-6"><div class="field-card"><label class="form-label">اسم المنشأة</label><input class="form-control" value="{{ $company->name_ar ?: $company->legal_name_ar }}" placeholder="اسم المنشأة" disabled><div class="form-text">يتم تعديل البيانات القانونية من شاشة إدارة المنشأة.</div></div></div><div class="col-lg-6"><div class="field-card"><label class="form-label">الرقم الضريبي</label><input class="form-control" value="{{ $company->tax_number }}" placeholder="الرقم الضريبي" disabled></div></div><div class="col-lg-6"><div class="field-card"><label class="form-label">شعار المنشأة</label><div class="preview-box"><input type="hidden" name="settings[company_logo]" value="{{ $value('company_logo') }}"><input class="form-control" type="file" accept="image/*" name="company_logo_file" data-image-input data-preview="company-logo-preview"><div class="form-text mt-2">PNG/JPG/WEBP حتى 2MB.</div><img id="company-logo-preview" class="mt-2" src="{{ $value('company_logo') ? asset('storage/'.$value('company_logo')) : asset('assets/images/invoice-placeholder-logo.svg') }}" alt="شعار المنشأة"></div></div></div><div class="col-lg-6"><div class="field-card"><label class="form-label">نص تذييل عام</label><textarea class="form-control" rows="5" name="settings[invoice_footer_text]" placeholder="مثال: شكراً لتعاملكم معنا">{{ $value('invoice_footer_text') }}</textarea><div class="form-text">يظهر في قوالب الفواتير عند الحاجة.</div></div></div></div>
    </div>
    <div class="settings-panel" data-panel="branding">
        <div class="section-title"><span class="icon">🎨</span><div><h2>الهوية البصرية</h2><p>اجعل ألوان وشعارات الفاتورة متناسقة مع علامة المنشأة.</p></div></div>
        <div class="row g-3"><div class="col-md-4"><div class="field-card"><label class="form-label">لون الهوية</label><input class="form-control form-control-color w-100" type="color" name="settings[brand_color]" value="{{ $value('brand_color', '#00a9c4') ?: '#00a9c4' }}"><div class="form-text">اللون العام للمنشأة.</div></div></div><div class="col-md-4"><div class="field-card"><label class="form-label">لون الفاتورة الأساسي</label><input class="form-control form-control-color w-100" type="color" name="settings[invoice_primary_color]" value="{{ $value('invoice_primary_color', '#00a9c4') ?: '#00a9c4' }}"></div></div><div class="col-md-4"><div class="field-card"><label class="form-label">لون الفاتورة الثانوي</label><input class="form-control form-control-color w-100" type="color" name="settings[invoice_secondary_color]" value="{{ $value('invoice_secondary_color', '#12c2b2') ?: '#12c2b2' }}"></div></div><div class="col-lg-6"><div class="field-card"><label class="form-label">شعار الفاتورة</label><div class="preview-box"><input type="hidden" name="settings[invoice_logo]" value="{{ $value('invoice_logo') }}"><input class="form-control" type="file" accept="image/*" name="invoice_logo_file" data-image-input data-preview="invoice-logo-preview"><div class="form-text mt-2">يستخدم في رأس الفاتورة.</div><img id="invoice-logo-preview" class="mt-2" src="{{ $value('invoice_logo') ? asset('storage/'.$value('invoice_logo')) : asset('assets/images/invoice-placeholder-logo.svg') }}" alt="شعار الفاتورة"></div></div></div><div class="col-lg-6"><div class="field-card"><label class="form-label">صورة الختم</label><div class="preview-box"><input type="hidden" name="settings[invoice_stamp_image]" value="{{ $value('invoice_stamp_image') }}"><input class="form-control" type="file" accept="image/*" name="invoice_stamp_image_file" data-image-input data-preview="stamp-preview"><div class="form-text mt-2">اختياري ويظهر في منطقة التوقيع.</div><img id="stamp-preview" class="mt-2" src="{{ $value('invoice_stamp_image') ? asset('storage/'.$value('invoice_stamp_image')) : asset('assets/images/invoice-placeholder-logo.svg') }}" alt="ختم المنشأة"></div></div></div></div>
    </div>
    <div class="settings-panel" data-panel="invoice">
        <div class="section-title"><span class="icon">🧾</span><div><h2>إعدادات الفواتير</h2><p>نظّم ترقيم الفواتير والنصوص التي تظهر للعميل.</p></div></div>
        <div class="row g-3"><div class="col-lg-6"><div class="field-card"><label class="form-label">قالب الفاتورة الافتراضي</label><input class="form-control" name="settings[invoice_template_id]" placeholder="مثال: arabic-classic أو رقم القالب" value="{{ $value('invoice_template_id') }}"><div class="form-text">يمكن أيضاً اختيار القالب من صفحة قوالب الفواتير.</div></div></div><div class="col-lg-6"><div class="field-card"><label class="form-label">بادئة الفاتورة</label><input class="form-control" name="settings[invoice_prefix]" placeholder="مثال: INV" value="{{ $value('invoice_prefix', 'INV') }}"></div></div><div class="col-12"><div class="field-card"><label class="form-label">الشروط والأحكام</label><textarea class="form-control" rows="5" name="settings[invoice_terms_and_conditions]" placeholder="اكتب شروط الدفع والتسليم أو أي ملاحظات قانونية">{{ $value('invoice_terms_and_conditions') }}</textarea></div></div><div class="col-12"><div class="field-card"><label class="form-label">كتلة التوقيع</label><textarea class="form-control" rows="3" name="settings[invoice_signature_block]" placeholder="مثال: المدير المالي / الختم الرسمي">{{ $value('invoice_signature_block') }}</textarea></div></div></div>
    </div>
    <div class="settings-panel" data-panel="jofotara">
        <div class="section-title"><span class="icon">🔗</span><div><h2>إعدادات جوفوتارا</h2><p>تحقق من وضع الربط وحالة بيانات الاتصال دون كشف الأسرار.</p></div></div>
        <div class="row g-3"><div class="col-lg-6"><div class="field-card"><label class="form-label">وضع جوفوتارا</label><select class="form-select" name="settings[jofotara_mode]"><option value="sandbox" @selected($value('jofotara_mode', 'sandbox') === 'sandbox')>تجريبي</option><option value="production" @selected($value('jofotara_mode') === 'production')>إنتاجي</option></select><div class="form-text">هذا الخيار للعرض والإعدادات فقط ولا يغيّر منطق الإرسال.</div></div></div><div class="col-lg-6"><div class="secret-status"><div class="mb-1">حالة بيانات الربط: <strong>{{ $company->hasJofotaraClientId() && $company->hasJofotaraSecretKey() && filled($company->jofotara_source_id) ? 'محفوظة ومكتملة' : 'غير مكتملة' }}</strong></div><small class="text-muted">لا يتم عرض أي معرفات أو مفاتيح سرية في هذه الصفحة.</small></div></div></div>
    </div>
    <div class="settings-panel" data-panel="locale">
        <div class="section-title"><span class="icon">🌐</span><div><h2>اللغة والعملة</h2><p>اختر لغة النظام والعملة الافتراضية من قائمة جاهزة وواضحة.</p></div></div>
        <div class="row g-3"><div class="col-lg-6"><div class="field-card"><label class="form-label">اللغة الافتراضية</label><select class="form-select" name="settings[default_language]" required><option value="ar" @selected($value('default_language', $company->default_language ?: 'ar') === 'ar')>العربية</option><option value="en" @selected($value('default_language') === 'en')>English</option></select><div class="form-text">تؤثر على واجهات ونصوص المنشأة الافتراضية.</div></div></div><div class="col-lg-6"><div class="field-card"><label class="form-label">العملة الافتراضية</label><div class="currency-select-wrap"><select class="form-select" name="settings[default_currency]" required>@foreach($currencyOptions as $currency)<option value="{{ $currency->code }}" @selected($selectedCurrency === $currency->code)>{{ $currency->code }} — {{ $currency->name }}</option>@endforeach</select></div><div class="form-text">سيتم استخدامها كعملة افتراضية للفواتير والمنتجات الجديدة.</div></div></div></div>
    </div>
    <div class="settings-actions d-flex flex-wrap gap-2"><button class="btn btn-primary">حفظ الإعدادات</button><a class="btn btn-outline-secondary" href="{{ route('company.dashboard', ['company' => $routeCompanyId]) }}">إلغاء</a></div>
</form>
<script>
document.addEventListener('DOMContentLoaded',function(){var form=document.querySelector('[data-settings-form]');if(!form)return;var tabs=form.querySelectorAll('[data-tab]');var panels=form.querySelectorAll('[data-panel]');tabs.forEach(function(tab){tab.addEventListener('click',function(){tabs.forEach(function(t){t.classList.remove('active')});panels.forEach(function(p){p.classList.remove('active')});tab.classList.add('active');form.querySelector('[data-panel="'+tab.dataset.tab+'"]').classList.add('active');});});form.querySelectorAll('[data-image-input]').forEach(function(input){input.addEventListener('change',function(){var file=input.files[0];var summary=form.querySelector('[data-validation-summary]');if(!file)return;if(!file.type.startsWith('image/')||file.size>2*1024*1024){summary.style.display='block';summary.innerHTML='<div>الصورة يجب أن تكون ملف صورة وحجمها لا يتجاوز 2MB.</div>';input.value='';return;}var img=document.getElementById(input.dataset.preview);if(img)img.src=URL.createObjectURL(file);summary.style.display='none';});});});
</script>
@endsection
